apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-fosm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-fosm
    app.kubernetes.io/part-of: ci1t-830-0063-app
  name: devfile-sample-fosm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-fosm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-fosm
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0063-tenant/ci1t-830-0063-app/devfile-sample-fosm@sha256:ffa0506dfaedff5a7a9897d4a5694e5ab30ac53c214f3ecf0f4331c0cccebf6d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
